# RabbitMQ cluster used by the Source
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: chat-demo
  annotations:
    # We allow any Knative Broker of class RabbitMQBroker,
    # in any namespace,
    # to declare objects against this RabbitMQ cluster
    rabbitmq.com/topology-allowed-namespaces: "*"
spec:
  replicas: 1
