apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: knative-go-chat-app
  namespace: chat-demo
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "1"
    spec:
      containers:
      - image: ko://github.com/gabo1208/knative-go-chat-app/cmd/knative-go-chat-app
        env:
        - name: OWN_BROKER_URI
          value: "http://chat-broker-broker-ingress.chat-demo.svc.cluster.local"
        - name: CLUSTERS_BROKERS_URI
          value: "http://chat-broker-broker-ingress.default.svc.cluster.local"
