apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: go-chat-client
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "1"
    spec:
      containers:
        - image: ko://github.com/gabo1208/golang/knative/chat-client/cmd/go-chat-client