apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: knative-go-chat-app
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: ko://github.com/gabo1208/knative-go-chat-app/cmd/knative-go-chat-app
