apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sockeye
  namespace: chat-demo
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "1"
    spec:
      containers:
        - image: ko://github.com/n3wscott/sockeye/cmd/sockeye
